# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enterInfo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnterInfo(object):
    def setupUi(self, EnterInfo):
        EnterInfo.setObjectName("EnterInfo")
        EnterInfo.resize(487, 355)
        self.tabWidgetEnterInfo = QtWidgets.QTabWidget(EnterInfo)
        self.tabWidgetEnterInfo.setGeometry(QtCore.QRect(10, 10, 471, 341))
        self.tabWidgetEnterInfo.setMinimumSize(QtCore.QSize(471, 341))
        self.tabWidgetEnterInfo.setMaximumSize(QtCore.QSize(471, 341))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.tabWidgetEnterInfo.setFont(font)
        self.tabWidgetEnterInfo.setStyleSheet("border-radius:5px;\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 255);\n"
"selection-color: rgb(0, 0, 0);")
        self.tabWidgetEnterInfo.setObjectName("tabWidgetEnterInfo")
        self.tabServers = QtWidgets.QWidget()
        self.tabServers.setObjectName("tabServers")
        self.groupBoxServer = QtWidgets.QGroupBox(self.tabServers)
        self.groupBoxServer.setGeometry(QtCore.QRect(0, 0, 471, 341))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxServer.setFont(font)
        self.groupBoxServer.setStyleSheet("border-radius:5px;\n"
"background-color: lightgray;")
        self.groupBoxServer.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxServer.setObjectName("groupBoxServer")
        self.labelSelectServerOS = QtWidgets.QLabel(self.groupBoxServer)
        self.labelSelectServerOS.setGeometry(QtCore.QRect(20, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelSelectServerOS.setFont(font)
        self.labelSelectServerOS.setObjectName("labelSelectServerOS")
        self.comboBoxSelectServerOS = QtWidgets.QComboBox(self.groupBoxServer)
        self.comboBoxSelectServerOS.setGeometry(QtCore.QRect(80, 30, 91, 22))
        self.comboBoxSelectServerOS.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxSelectServerOS.setObjectName("comboBoxSelectServerOS")
        self.comboBoxSelectServerOS.addItem("")
        self.comboBoxSelectServerOS.addItem("")
        self.comboBoxSelectServerOS.addItem("")
        self.comboBoxSelectServerOS.addItem("")
        self.labelServerVersion = QtWidgets.QLabel(self.groupBoxServer)
        self.labelServerVersion.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelServerVersion.setFont(font)
        self.labelServerVersion.setObjectName("labelServerVersion")
        self.labelServerIP = QtWidgets.QLabel(self.groupBoxServer)
        self.labelServerIP.setGeometry(QtCore.QRect(20, 90, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelServerIP.setFont(font)
        self.labelServerIP.setObjectName("labelServerIP")
        self.lineEditServerIP = QtWidgets.QLineEdit(self.groupBoxServer)
        self.lineEditServerIP.setGeometry(QtCore.QRect(80, 90, 251, 20))
        self.lineEditServerIP.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditServerIP.setClearButtonEnabled(True)
        self.lineEditServerIP.setObjectName("lineEditServerIP")
        self.labelServerUserName = QtWidgets.QLabel(self.groupBoxServer)
        self.labelServerUserName.setGeometry(QtCore.QRect(20, 120, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelServerUserName.setFont(font)
        self.labelServerUserName.setObjectName("labelServerUserName")
        self.lineEditServerUserName = QtWidgets.QLineEdit(self.groupBoxServer)
        self.lineEditServerUserName.setGeometry(QtCore.QRect(80, 120, 251, 20))
        self.lineEditServerUserName.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditServerUserName.setClearButtonEnabled(True)
        self.lineEditServerUserName.setObjectName("lineEditServerUserName")
        self.labelServerPassWord = QtWidgets.QLabel(self.groupBoxServer)
        self.labelServerPassWord.setGeometry(QtCore.QRect(20, 150, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelServerPassWord.setFont(font)
        self.labelServerPassWord.setObjectName("labelServerPassWord")
        self.lineEditServerPassWord = QtWidgets.QLineEdit(self.groupBoxServer)
        self.lineEditServerPassWord.setGeometry(QtCore.QRect(80, 150, 141, 20))
        self.lineEditServerPassWord.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditServerPassWord.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditServerPassWord.setClearButtonEnabled(True)
        self.lineEditServerPassWord.setObjectName("lineEditServerPassWord")
        self.labelServerEnsure = QtWidgets.QLabel(self.groupBoxServer)
        self.labelServerEnsure.setGeometry(QtCore.QRect(240, 150, 41, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelServerEnsure.setFont(font)
        self.labelServerEnsure.setObjectName("labelServerEnsure")
        self.lineEditServerEnsure = QtWidgets.QLineEdit(self.groupBoxServer)
        self.lineEditServerEnsure.setGeometry(QtCore.QRect(280, 150, 141, 20))
        self.lineEditServerEnsure.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditServerEnsure.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditServerEnsure.setClearButtonEnabled(True)
        self.lineEditServerEnsure.setObjectName("lineEditServerEnsure")
        self.labelServerDescription = QtWidgets.QLabel(self.groupBoxServer)
        self.labelServerDescription.setGeometry(QtCore.QRect(20, 180, 54, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelServerDescription.setFont(font)
        self.labelServerDescription.setObjectName("labelServerDescription")
        self.plainTextEditServerDescription = QtWidgets.QPlainTextEdit(self.groupBoxServer)
        self.plainTextEditServerDescription.setGeometry(QtCore.QRect(80, 180, 341, 71))
        self.plainTextEditServerDescription.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEditServerDescription.setObjectName("plainTextEditServerDescription")
        self.pushButtonServerEntry = QtWidgets.QPushButton(self.groupBoxServer)
        self.pushButtonServerEntry.setGeometry(QtCore.QRect(80, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonServerEntry.setFont(font)
        self.pushButtonServerEntry.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:5px;\n"
"color: rgb(255, 255, 255);")
        self.pushButtonServerEntry.setObjectName("pushButtonServerEntry")
        self.pushButtonServerQuit = QtWidgets.QPushButton(self.groupBoxServer)
        self.pushButtonServerQuit.setGeometry(QtCore.QRect(340, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonServerQuit.setFont(font)
        self.pushButtonServerQuit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);\n"
"border-radius:5px;")
        self.pushButtonServerQuit.setObjectName("pushButtonServerQuit")
        self.comboBoxSelectServerVersion = QtWidgets.QComboBox(self.groupBoxServer)
        self.comboBoxSelectServerVersion.setGeometry(QtCore.QRect(80, 60, 281, 22))
        self.comboBoxSelectServerVersion.setAutoFillBackground(False)
        self.comboBoxSelectServerVersion.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxSelectServerVersion.setEditable(False)
        self.comboBoxSelectServerVersion.setObjectName("comboBoxSelectServerVersion")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.comboBoxSelectServerVersion.addItem("")
        self.tabWidgetEnterInfo.addTab(self.tabServers, "")
        self.tabDatabases = QtWidgets.QWidget()
        self.tabDatabases.setObjectName("tabDatabases")
        self.groupBoxDB = QtWidgets.QGroupBox(self.tabDatabases)
        self.groupBoxDB.setGeometry(QtCore.QRect(0, 0, 471, 341))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxDB.setFont(font)
        self.groupBoxDB.setStyleSheet("border-radius:5px;\n"
"background-color: lightgray;")
        self.groupBoxDB.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxDB.setObjectName("groupBoxDB")
        self.labelSelectDB = QtWidgets.QLabel(self.groupBoxDB)
        self.labelSelectDB.setGeometry(QtCore.QRect(20, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelSelectDB.setFont(font)
        self.labelSelectDB.setObjectName("labelSelectDB")
        self.comboBoxSelectDB = QtWidgets.QComboBox(self.groupBoxDB)
        self.comboBoxSelectDB.setGeometry(QtCore.QRect(90, 30, 111, 22))
        self.comboBoxSelectDB.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxSelectDB.setObjectName("comboBoxSelectDB")
        self.comboBoxSelectDB.addItem("")
        self.comboBoxSelectDB.addItem("")
        self.comboBoxSelectDB.addItem("")
        self.comboBoxSelectDB.addItem("")
        self.comboBoxSelectDB.addItem("")
        self.comboBoxSelectDB.addItem("")
        self.labelDBVersion = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDBVersion.setGeometry(QtCore.QRect(20, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDBVersion.setFont(font)
        self.labelDBVersion.setObjectName("labelDBVersion")
        self.labelDBIP = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDBIP.setGeometry(QtCore.QRect(20, 90, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDBIP.setFont(font)
        self.labelDBIP.setObjectName("labelDBIP")
        self.lineEditDBIP = QtWidgets.QLineEdit(self.groupBoxDB)
        self.lineEditDBIP.setGeometry(QtCore.QRect(90, 90, 251, 20))
        self.lineEditDBIP.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditDBIP.setClearButtonEnabled(True)
        self.lineEditDBIP.setObjectName("lineEditDBIP")
        self.labelDBUserName = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDBUserName.setGeometry(QtCore.QRect(20, 120, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDBUserName.setFont(font)
        self.labelDBUserName.setObjectName("labelDBUserName")
        self.lineEditDBUserName = QtWidgets.QLineEdit(self.groupBoxDB)
        self.lineEditDBUserName.setGeometry(QtCore.QRect(90, 120, 251, 20))
        self.lineEditDBUserName.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditDBUserName.setClearButtonEnabled(True)
        self.lineEditDBUserName.setObjectName("lineEditDBUserName")
        self.labelDBPassWord = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDBPassWord.setGeometry(QtCore.QRect(20, 180, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDBPassWord.setFont(font)
        self.labelDBPassWord.setObjectName("labelDBPassWord")
        self.lineEditDBPassWord = QtWidgets.QLineEdit(self.groupBoxDB)
        self.lineEditDBPassWord.setGeometry(QtCore.QRect(90, 180, 141, 20))
        self.lineEditDBPassWord.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditDBPassWord.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditDBPassWord.setClearButtonEnabled(True)
        self.lineEditDBPassWord.setObjectName("lineEditDBPassWord")
        self.labelDBEnsure = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDBEnsure.setGeometry(QtCore.QRect(260, 180, 41, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDBEnsure.setFont(font)
        self.labelDBEnsure.setObjectName("labelDBEnsure")
        self.lineEditDBEnsure = QtWidgets.QLineEdit(self.groupBoxDB)
        self.lineEditDBEnsure.setGeometry(QtCore.QRect(290, 180, 141, 20))
        self.lineEditDBEnsure.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditDBEnsure.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditDBEnsure.setClearButtonEnabled(True)
        self.lineEditDBEnsure.setObjectName("lineEditDBEnsure")
        self.labelDBDescription = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDBDescription.setGeometry(QtCore.QRect(20, 210, 54, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDBDescription.setFont(font)
        self.labelDBDescription.setObjectName("labelDBDescription")
        self.plainTextEditDBDescription = QtWidgets.QPlainTextEdit(self.groupBoxDB)
        self.plainTextEditDBDescription.setGeometry(QtCore.QRect(90, 210, 341, 71))
        self.plainTextEditDBDescription.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEditDBDescription.setObjectName("plainTextEditDBDescription")
        self.pushButtonDBEntry = QtWidgets.QPushButton(self.groupBoxDB)
        self.pushButtonDBEntry.setGeometry(QtCore.QRect(90, 290, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDBEntry.setFont(font)
        self.pushButtonDBEntry.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"border-radius:5px;\n"
"color: rgb(0, 0, 0);")
        self.pushButtonDBEntry.setObjectName("pushButtonDBEntry")
        self.pushButtonDBQuit = QtWidgets.QPushButton(self.groupBoxDB)
        self.pushButtonDBQuit.setGeometry(QtCore.QRect(350, 290, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDBQuit.setFont(font)
        self.pushButtonDBQuit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 255, 0);\n"
"border-radius:5px;")
        self.pushButtonDBQuit.setObjectName("pushButtonDBQuit")
        self.comboBoxSelectDBVersion = QtWidgets.QComboBox(self.groupBoxDB)
        self.comboBoxSelectDBVersion.setGeometry(QtCore.QRect(90, 60, 251, 22))
        self.comboBoxSelectDBVersion.setAutoFillBackground(False)
        self.comboBoxSelectDBVersion.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxSelectDBVersion.setEditable(False)
        self.comboBoxSelectDBVersion.setObjectName("comboBoxSelectDBVersion")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.comboBoxSelectDBVersion.addItem("")
        self.labelDatabaseName = QtWidgets.QLabel(self.groupBoxDB)
        self.labelDatabaseName.setGeometry(QtCore.QRect(20, 150, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDatabaseName.setFont(font)
        self.labelDatabaseName.setObjectName("labelDatabaseName")
        self.lineEditDatabaseName = QtWidgets.QLineEdit(self.groupBoxDB)
        self.lineEditDatabaseName.setGeometry(QtCore.QRect(90, 150, 251, 20))
        self.lineEditDatabaseName.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditDatabaseName.setObjectName("lineEditDatabaseName")
        self.tabWidgetEnterInfo.addTab(self.tabDatabases, "")

        self.retranslateUi(EnterInfo)
        self.tabWidgetEnterInfo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(EnterInfo)

    def retranslateUi(self, EnterInfo):
        _translate = QtCore.QCoreApplication.translate
        EnterInfo.setWindowTitle(_translate("EnterInfo", "信息录入"))
        self.groupBoxServer.setTitle(_translate("EnterInfo", "服务器信息录入"))
        self.labelSelectServerOS.setText(_translate("EnterInfo", "系统类型"))
        self.comboBoxSelectServerOS.setItemText(0, _translate("EnterInfo", "Linux系统"))
        self.comboBoxSelectServerOS.setItemText(1, _translate("EnterInfo", "AIX系统"))
        self.comboBoxSelectServerOS.setItemText(2, _translate("EnterInfo", "Windows系统"))
        self.comboBoxSelectServerOS.setItemText(3, _translate("EnterInfo", "HP-UNIX系统"))
        self.labelServerVersion.setText(_translate("EnterInfo", "系统版本"))
        self.labelServerIP.setText(_translate("EnterInfo", "IP地址"))
        self.lineEditServerIP.setPlaceholderText(_translate("EnterInfo", "请输入服务器IP地址信息"))
        self.labelServerUserName.setText(_translate("EnterInfo", "账   号"))
        self.lineEditServerUserName.setPlaceholderText(_translate("EnterInfo", "请输入服务器登录账号"))
        self.labelServerPassWord.setText(_translate("EnterInfo", "密码"))
        self.lineEditServerPassWord.setPlaceholderText(_translate("EnterInfo", "请输入密码"))
        self.labelServerEnsure.setText(_translate("EnterInfo", "确认"))
        self.lineEditServerEnsure.setPlaceholderText(_translate("EnterInfo", "请再次输入密码确认"))
        self.labelServerDescription.setText(_translate("EnterInfo", "描述"))
        self.plainTextEditServerDescription.setPlaceholderText(_translate("EnterInfo", "请输入服务器描述信息"))
        self.pushButtonServerEntry.setText(_translate("EnterInfo", "录入"))
        self.pushButtonServerQuit.setText(_translate("EnterInfo", "取消"))
        self.comboBoxSelectServerVersion.setItemText(0, _translate("EnterInfo", "Red Hat Enterprise Linux release 6"))
        self.comboBoxSelectServerVersion.setItemText(1, _translate("EnterInfo", "Red Hat Enterprise Linux release 7"))
        self.comboBoxSelectServerVersion.setItemText(2, _translate("EnterInfo", "Red Hat Enterprise Linux release 8"))
        self.comboBoxSelectServerVersion.setItemText(3, _translate("EnterInfo", "CentOS Linux release 6"))
        self.comboBoxSelectServerVersion.setItemText(4, _translate("EnterInfo", "CentOS Linux release 7"))
        self.comboBoxSelectServerVersion.setItemText(5, _translate("EnterInfo", "CentOS Linux release 8"))
        self.comboBoxSelectServerVersion.setItemText(6, _translate("EnterInfo", "SUSE Linux 11"))
        self.comboBoxSelectServerVersion.setItemText(7, _translate("EnterInfo", "SUSE Linux 12"))
        self.comboBoxSelectServerVersion.setItemText(8, _translate("EnterInfo", "AIX Version 6"))
        self.comboBoxSelectServerVersion.setItemText(9, _translate("EnterInfo", "AIX Version 7"))
        self.comboBoxSelectServerVersion.setItemText(10, _translate("EnterInfo", "Windows Server 2003 32位"))
        self.comboBoxSelectServerVersion.setItemText(11, _translate("EnterInfo", "Windows Server 2003 64位"))
        self.comboBoxSelectServerVersion.setItemText(12, _translate("EnterInfo", "Windows Server 2008 32位"))
        self.comboBoxSelectServerVersion.setItemText(13, _translate("EnterInfo", "Windows Server 2008 64位"))
        self.comboBoxSelectServerVersion.setItemText(14, _translate("EnterInfo", "Windows Server 2012 32位"))
        self.comboBoxSelectServerVersion.setItemText(15, _translate("EnterInfo", "Windows Server 2012 64位"))
        self.comboBoxSelectServerVersion.setItemText(16, _translate("EnterInfo", "Windows Server 2016 32位"))
        self.comboBoxSelectServerVersion.setItemText(17, _translate("EnterInfo", "Windows Server 2016 64位"))
        self.comboBoxSelectServerVersion.setItemText(18, _translate("EnterInfo", "Windows XP 32位"))
        self.comboBoxSelectServerVersion.setItemText(19, _translate("EnterInfo", "Windows XP 64位"))
        self.comboBoxSelectServerVersion.setItemText(20, _translate("EnterInfo", "Windows 7 32位"))
        self.comboBoxSelectServerVersion.setItemText(21, _translate("EnterInfo", "Windows 7 64位"))
        self.comboBoxSelectServerVersion.setItemText(22, _translate("EnterInfo", "Windows 10 32位"))
        self.comboBoxSelectServerVersion.setItemText(23, _translate("EnterInfo", "Windows 10 64位"))
        self.comboBoxSelectServerVersion.setItemText(24, _translate("EnterInfo", "Others"))
        self.tabWidgetEnterInfo.setTabText(self.tabWidgetEnterInfo.indexOf(self.tabServers), _translate("EnterInfo", "服务器信息录入"))
        self.groupBoxDB.setTitle(_translate("EnterInfo", "数据库信息录入"))
        self.labelSelectDB.setText(_translate("EnterInfo", "数据库类型"))
        self.comboBoxSelectDB.setItemText(0, _translate("EnterInfo", "DB2 数据库"))
        self.comboBoxSelectDB.setItemText(1, _translate("EnterInfo", "Oracle 数据库"))
        self.comboBoxSelectDB.setItemText(2, _translate("EnterInfo", "MySQL 数据库"))
        self.comboBoxSelectDB.setItemText(3, _translate("EnterInfo", "SQL Server 数据库"))
        self.comboBoxSelectDB.setItemText(4, _translate("EnterInfo", "MongoDB 数据库"))
        self.comboBoxSelectDB.setItemText(5, _translate("EnterInfo", "Couchbase 数据库"))
        self.labelDBVersion.setText(_translate("EnterInfo", "数据库版本"))
        self.labelDBIP.setText(_translate("EnterInfo", "IP地址"))
        self.lineEditDBIP.setPlaceholderText(_translate("EnterInfo", "请输入服务器IP地址信息"))
        self.labelDBUserName.setText(_translate("EnterInfo", "数据库账号"))
        self.lineEditDBUserName.setPlaceholderText(_translate("EnterInfo", "请输入服务器登录账号"))
        self.labelDBPassWord.setText(_translate("EnterInfo", "数据库密码"))
        self.lineEditDBPassWord.setPlaceholderText(_translate("EnterInfo", "请输入密码"))
        self.labelDBEnsure.setText(_translate("EnterInfo", "确认"))
        self.lineEditDBEnsure.setPlaceholderText(_translate("EnterInfo", "请再次输入密码确认"))
        self.labelDBDescription.setText(_translate("EnterInfo", "描述"))
        self.plainTextEditDBDescription.setPlaceholderText(_translate("EnterInfo", "请输入服务器描述信息"))
        self.pushButtonDBEntry.setText(_translate("EnterInfo", "录入"))
        self.pushButtonDBQuit.setText(_translate("EnterInfo", "取消"))
        self.comboBoxSelectDBVersion.setItemText(0, _translate("EnterInfo", "Oracle 9i"))
        self.comboBoxSelectDBVersion.setItemText(1, _translate("EnterInfo", "Oracle 10g"))
        self.comboBoxSelectDBVersion.setItemText(2, _translate("EnterInfo", "Oracle 11g"))
        self.comboBoxSelectDBVersion.setItemText(3, _translate("EnterInfo", "Oracle 12c"))
        self.comboBoxSelectDBVersion.setItemText(4, _translate("EnterInfo", "Oracle 18c"))
        self.comboBoxSelectDBVersion.setItemText(5, _translate("EnterInfo", "Oracle 19c"))
        self.comboBoxSelectDBVersion.setItemText(6, _translate("EnterInfo", "DB2 8.2.0"))
        self.comboBoxSelectDBVersion.setItemText(7, _translate("EnterInfo", "DB2 9.1.0"))
        self.comboBoxSelectDBVersion.setItemText(8, _translate("EnterInfo", "DB2 9.7.0"))
        self.comboBoxSelectDBVersion.setItemText(9, _translate("EnterInfo", "DB2 10.1.0"))
        self.comboBoxSelectDBVersion.setItemText(10, _translate("EnterInfo", "DB2 10.5.0"))
        self.comboBoxSelectDBVersion.setItemText(11, _translate("EnterInfo", "DB2 10.5.0.4"))
        self.comboBoxSelectDBVersion.setItemText(12, _translate("EnterInfo", "DB2 11.1"))
        self.comboBoxSelectDBVersion.setItemText(13, _translate("EnterInfo", "DB2 11.5"))
        self.comboBoxSelectDBVersion.setItemText(14, _translate("EnterInfo", "MySQL 5.6"))
        self.comboBoxSelectDBVersion.setItemText(15, _translate("EnterInfo", "MySQL 5.7"))
        self.comboBoxSelectDBVersion.setItemText(16, _translate("EnterInfo", "MySQL 8.0"))
        self.comboBoxSelectDBVersion.setItemText(17, _translate("EnterInfo", "SQL Server 6.5"))
        self.comboBoxSelectDBVersion.setItemText(18, _translate("EnterInfo", "SQL Server 7.0"))
        self.comboBoxSelectDBVersion.setItemText(19, _translate("EnterInfo", "SQL Server 2000"))
        self.comboBoxSelectDBVersion.setItemText(20, _translate("EnterInfo", "SQL Server 2008"))
        self.comboBoxSelectDBVersion.setItemText(21, _translate("EnterInfo", "SQL Server 2012"))
        self.comboBoxSelectDBVersion.setItemText(22, _translate("EnterInfo", "SQL Server 2014"))
        self.comboBoxSelectDBVersion.setItemText(23, _translate("EnterInfo", "SQL Server 2018"))
        self.comboBoxSelectDBVersion.setItemText(24, _translate("EnterInfo", "MongoDB Community 3.0.x"))
        self.comboBoxSelectDBVersion.setItemText(25, _translate("EnterInfo", "MongoDB Community 3.2.x"))
        self.comboBoxSelectDBVersion.setItemText(26, _translate("EnterInfo", "MongoDB Community 3.4.x"))
        self.comboBoxSelectDBVersion.setItemText(27, _translate("EnterInfo", "MongoDB Community 3.6.x"))
        self.comboBoxSelectDBVersion.setItemText(28, _translate("EnterInfo", "MongoDB Community 4.0.x"))
        self.comboBoxSelectDBVersion.setItemText(29, _translate("EnterInfo", "MongoDB Community 4.2.x"))
        self.comboBoxSelectDBVersion.setItemText(30, _translate("EnterInfo", "MongoDB Community 4.3.x"))
        self.comboBoxSelectDBVersion.setItemText(31, _translate("EnterInfo", "MongoDB Community 4.4.x"))
        self.labelDatabaseName.setText(_translate("EnterInfo", "数据库实例"))
        self.lineEditDatabaseName.setPlaceholderText(_translate("EnterInfo", "请输入数据库实例名称"))
        self.tabWidgetEnterInfo.setTabText(self.tabWidgetEnterInfo.indexOf(self.tabDatabases), _translate("EnterInfo", "数据库信息录入"))

