# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enterInfo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_enterInfo(object):
    def setupUi(self, enterInfo):
        enterInfo.setObjectName("enterInfo")
        enterInfo.setEnabled(True)
        enterInfo.resize(474, 324)
        enterInfo.setFixedSize(474, 324)
        self.groupBox = QtWidgets.QGroupBox(enterInfo)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 301))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-radius:5px;\n"
"background-color: lightgray;")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEditVersion = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditVersion.setGeometry(QtCore.QRect(80, 60, 251, 20))
        self.lineEditVersion.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditVersion.setClearButtonEnabled(True)
        self.lineEditVersion.setObjectName("lineEditVersion")
        self.labelSelectOS = QtWidgets.QLabel(self.groupBox)
        self.labelSelectOS.setGeometry(QtCore.QRect(20, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelSelectOS.setFont(font)
        self.labelSelectOS.setObjectName("labelSelectOS")
        self.comboBoxSelectOS = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxSelectOS.setGeometry(QtCore.QRect(80, 30, 91, 22))
        self.comboBoxSelectOS.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxSelectOS.setObjectName("comboBoxSelectOS")
        self.comboBoxSelectOS.addItem("")
        self.comboBoxSelectOS.addItem("")
        self.comboBoxSelectOS.addItem("")
        self.comboBoxSelectOS.addItem("")
        self.labelVersion = QtWidgets.QLabel(self.groupBox)
        self.labelVersion.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelVersion.setFont(font)
        self.labelVersion.setObjectName("labelVersion")
        self.labelIP = QtWidgets.QLabel(self.groupBox)
        self.labelIP.setGeometry(QtCore.QRect(20, 90, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelIP.setFont(font)
        self.labelIP.setObjectName("labelIP")
        self.lineEditIP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditIP.setGeometry(QtCore.QRect(80, 90, 251, 20))
        self.lineEditIP.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditIP.setClearButtonEnabled(True)
        self.lineEditIP.setObjectName("lineEditIP")
        self.labelUserName = QtWidgets.QLabel(self.groupBox)
        self.labelUserName.setGeometry(QtCore.QRect(20, 120, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelUserName.setFont(font)
        self.labelUserName.setObjectName("labelUserName")
        self.lineEditUserName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditUserName.setGeometry(QtCore.QRect(80, 120, 251, 20))
        self.lineEditUserName.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditUserName.setClearButtonEnabled(True)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.labelPassWord = QtWidgets.QLabel(self.groupBox)
        self.labelPassWord.setGeometry(QtCore.QRect(20, 150, 54, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelPassWord.setFont(font)
        self.labelPassWord.setObjectName("labelPassWord")
        self.lineEditPassWord = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditPassWord.setGeometry(QtCore.QRect(80, 150, 141, 20))
        self.lineEditPassWord.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditPassWord.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassWord.setClearButtonEnabled(True)
        self.lineEditPassWord.setObjectName("lineEditPassWord")
        self.labelEnsure = QtWidgets.QLabel(self.groupBox)
        self.labelEnsure.setGeometry(QtCore.QRect(240, 150, 41, 16))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelEnsure.setFont(font)
        self.labelEnsure.setObjectName("labelEnsure")
        self.lineEditEnsure = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditEnsure.setGeometry(QtCore.QRect(280, 150, 141, 20))
        self.lineEditEnsure.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEditEnsure.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditEnsure.setClearButtonEnabled(True)
        self.lineEditEnsure.setObjectName("lineEditEnsure")
        self.labelDescription = QtWidgets.QLabel(self.groupBox)
        self.labelDescription.setGeometry(QtCore.QRect(20, 180, 54, 21))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.labelDescription.setFont(font)
        self.labelDescription.setObjectName("labelDescription")
        self.plainTextEditDescription = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEditDescription.setGeometry(QtCore.QRect(80, 180, 341, 71))
        self.plainTextEditDescription.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEditDescription.setObjectName("plainTextEditDescription")
        self.pushButtonEntry = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonEntry.setGeometry(QtCore.QRect(80, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEntry.setFont(font)
        self.pushButtonEntry.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:5px;\n"
"color: rgb(255, 255, 255);")
        self.pushButtonEntry.setObjectName("pushButtonEntry")
        self.pushButtonQuit = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonQuit.setGeometry(QtCore.QRect(350, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonQuit.setFont(font)
        self.pushButtonQuit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);\n"
"border-radius:5px;")
        self.pushButtonQuit.setObjectName("pushButtonQuit")

        self.retranslateUi(enterInfo)
        QtCore.QMetaObject.connectSlotsByName(enterInfo)

    def retranslateUi(self, enterInfo):
        _translate = QtCore.QCoreApplication.translate
        enterInfo.setWindowTitle(_translate("enterInfo", "信息录入"))
        enterInfo.setWindowIcon(QtGui.QIcon('login.ico'))
        self.groupBox.setTitle(_translate("enterInfo", "基本信息录入"))
        self.lineEditVersion.setPlaceholderText(_translate("enterInfo", "请输入操作系统版本"))
        self.labelSelectOS.setText(_translate("enterInfo", "系统类型"))
        self.comboBoxSelectOS.setItemText(0, _translate("enterInfo", "Linux系统"))
        self.comboBoxSelectOS.setItemText(1, _translate("enterInfo", "AIX系统"))
        self.comboBoxSelectOS.setItemText(2, _translate("enterInfo", "Windows系统"))
        self.comboBoxSelectOS.setItemText(3, _translate("enterInfo", "HP-UNIX系统"))
        self.labelVersion.setText(_translate("enterInfo", "系统版本"))
        self.labelIP.setText(_translate("enterInfo", "IP地址"))
        self.lineEditIP.setPlaceholderText(_translate("enterInfo", "请输入服务器IP地址信息"))
        self.labelUserName.setText(_translate("enterInfo", "账   号"))
        self.lineEditUserName.setPlaceholderText(_translate("enterInfo", "请输入服务器登录账号"))
        self.labelPassWord.setText(_translate("enterInfo", "密码"))
        self.lineEditPassWord.setPlaceholderText(_translate("enterInfo", "请输入密码"))
        self.labelEnsure.setText(_translate("enterInfo", "确认"))
        self.lineEditEnsure.setPlaceholderText(_translate("enterInfo", "请再次输入密码确认"))
        self.labelDescription.setText(_translate("enterInfo", "描述"))
        self.plainTextEditDescription.setPlaceholderText(_translate("enterInfo", "请输入服务器描述信息"))
        self.pushButtonEntry.setText(_translate("enterInfo", "录入"))
        self.pushButtonQuit.setText(_translate("enterInfo", "取消"))
