# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1185, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1090, 800))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 785))
        MainWindow.setBaseSize(QtCore.QSize(1090, 785))
        self.mainWindows = QtWidgets.QWidget(MainWindow)
        self.mainWindows.setObjectName("mainWindows")
        self.labelProperty = QtWidgets.QLabel(self.mainWindows)
        self.labelProperty.setGeometry(QtCore.QRect(510, 0, 71, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelProperty.setFont(font)
        self.labelProperty.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(85, 170, 255);")
        self.labelProperty.setObjectName("labelProperty")
        self.widgetGraph = QtWebEngineWidgets.QWebEngineView(self.mainWindows)
        self.widgetGraph.setGeometry(QtCore.QRect(10, 385, 1171, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetGraph.sizePolicy().hasHeightForWidth())
        self.widgetGraph.setSizePolicy(sizePolicy)
        self.widgetGraph.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.widgetGraph.setObjectName("widgetGraph")
        self.labelPropertyGraph = QtWidgets.QLabel(self.mainWindows)
        self.labelPropertyGraph.setGeometry(QtCore.QRect(510, 360, 71, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelPropertyGraph.setFont(font)
        self.labelPropertyGraph.setStyleSheet("font: 13pt \"幼圆\";\n"
"color: rgb(255, 170, 0);")
        self.labelPropertyGraph.setObjectName("labelPropertyGraph")
        self.tabWidget = QtWidgets.QTabWidget(self.mainWindows)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1171, 351))
        self.tabWidget.setStyleSheet("font: 10pt \"华文中宋\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableViewServersProperty = QtWidgets.QTableView(self.tab)
        self.tableViewServersProperty.setGeometry(QtCore.QRect(0, 30, 1170, 271))
        self.tableViewServersProperty.setAutoFillBackground(True)
        self.tableViewServersProperty.setStyleSheet("border-radius:5px;\n"
"font: 11pt \"华文中宋\";\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"selection-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(130, 130, 130);\n"
"")
        self.tableViewServersProperty.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableViewServersProperty.setDragEnabled(True)
        self.tableViewServersProperty.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableViewServersProperty.setSortingEnabled(True)
        self.tableViewServersProperty.setObjectName("tableViewServersProperty")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 367, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonServerPrevPage = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonServerPrevPage.setObjectName("pushButtonServerPrevPage")
        self.horizontalLayout.addWidget(self.pushButtonServerPrevPage)
        self.pushButtonServerNextPage = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonServerNextPage.setObjectName("pushButtonServerNextPage")
        self.horizontalLayout.addWidget(self.pushButtonServerNextPage)
        self.labelSwitchPage = QtWidgets.QLabel(self.layoutWidget)
        self.labelSwitchPage.setObjectName("labelSwitchPage")
        self.horizontalLayout.addWidget(self.labelSwitchPage)
        self.lineEditPageNumber = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPageNumber.setObjectName("lineEditPageNumber")
        self.horizontalLayout.addWidget(self.lineEditPageNumber)
        self.labelPage = QtWidgets.QLabel(self.layoutWidget)
        self.labelPage.setObjectName("labelPage")
        self.horizontalLayout.addWidget(self.labelPage)
        self.pushButtonGO = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonGO.setObjectName("pushButtonGO")
        self.horizontalLayout.addWidget(self.pushButtonGO)
        self.labelServerCurrentPage = QtWidgets.QLabel(self.tab)
        self.labelServerCurrentPage.setGeometry(QtCore.QRect(100, 305, 81, 16))
        self.labelServerCurrentPage.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius:5px;")
        self.labelServerCurrentPage.setText("")
        self.labelServerCurrentPage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelServerCurrentPage.setObjectName("labelServerCurrentPage")
        self.labelServerTotalPages = QtWidgets.QLabel(self.tab)
        self.labelServerTotalPages.setGeometry(QtCore.QRect(10, 305, 81, 16))
        self.labelServerTotalPages.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius:5px;")
        self.labelServerTotalPages.setText("")
        self.labelServerTotalPages.setAlignment(QtCore.Qt.AlignCenter)
        self.labelServerTotalPages.setObjectName("labelServerTotalPages")
        self.labelServerTotalItems = QtWidgets.QLabel(self.tab)
        self.labelServerTotalItems.setGeometry(QtCore.QRect(1010, 305, 81, 16))
        self.labelServerTotalItems.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius:5px;")
        self.labelServerTotalItems.setText("")
        self.labelServerTotalItems.setAlignment(QtCore.Qt.AlignCenter)
        self.labelServerTotalItems.setObjectName("labelServerTotalItems")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 367, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonDBPrevPage = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonDBPrevPage.setObjectName("pushButtonDBPrevPage")
        self.horizontalLayout_2.addWidget(self.pushButtonDBPrevPage)
        self.pushButtonDBNextPage = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonDBNextPage.setObjectName("pushButtonDBNextPage")
        self.horizontalLayout_2.addWidget(self.pushButtonDBNextPage)
        self.labelDBSwitchPage = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelDBSwitchPage.setObjectName("labelDBSwitchPage")
        self.horizontalLayout_2.addWidget(self.labelDBSwitchPage)
        self.lineEditDBPageNumber = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEditDBPageNumber.setObjectName("lineEditDBPageNumber")
        self.horizontalLayout_2.addWidget(self.lineEditDBPageNumber)
        self.labelDBPage = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelDBPage.setObjectName("labelDBPage")
        self.horizontalLayout_2.addWidget(self.labelDBPage)
        self.pushButtonDBGO = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButtonDBGO.setObjectName("pushButtonDBGO")
        self.horizontalLayout_2.addWidget(self.pushButtonDBGO)
        self.tableViewDBProperty = QtWidgets.QTableView(self.tab_2)
        self.tableViewDBProperty.setGeometry(QtCore.QRect(0, 30, 1170, 271))
        self.tableViewDBProperty.setAutoFillBackground(True)
        self.tableViewDBProperty.setStyleSheet("border-radius:5px;\n"
"font: 11pt \"华文中宋\";\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"selection-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(130, 130, 130);\n"
"")
        self.tableViewDBProperty.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableViewDBProperty.setDragEnabled(True)
        self.tableViewDBProperty.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableViewDBProperty.setSortingEnabled(True)
        self.tableViewDBProperty.setObjectName("tableViewDBProperty")
        self.labelDBTotalPages = QtWidgets.QLabel(self.tab_2)
        self.labelDBTotalPages.setGeometry(QtCore.QRect(10, 305, 81, 16))
        self.labelDBTotalPages.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius:5px;")
        self.labelDBTotalPages.setText("")
        self.labelDBTotalPages.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDBTotalPages.setObjectName("labelDBTotalPages")
        self.labelDBCurrentPage = QtWidgets.QLabel(self.tab_2)
        self.labelDBCurrentPage.setGeometry(QtCore.QRect(100, 305, 81, 16))
        self.labelDBCurrentPage.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius:5px;")
        self.labelDBCurrentPage.setText("")
        self.labelDBCurrentPage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDBCurrentPage.setObjectName("labelDBCurrentPage")
        self.labelDBTotalItems = QtWidgets.QLabel(self.tab_2)
        self.labelDBTotalItems.setGeometry(QtCore.QRect(1010, 305, 81, 16))
        self.labelDBTotalItems.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border-radius:5px;")
        self.labelDBTotalItems.setText("")
        self.labelDBTotalItems.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDBTotalItems.setObjectName("labelDBTotalItems")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.mainWindows)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.File.setFont(font)
        self.File.setObjectName("File")
        self.Tool = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.Tool.setFont(font)
        self.Tool.setObjectName("Tool")
        self.Help = QtWidgets.QMenu(self.menubar)
        self.Help.setObjectName("Help")
        self.Check = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.Check.setFont(font)
        self.Check.setObjectName("Check")
        self.Setup = QtWidgets.QMenu(self.menubar)
        self.Setup.setObjectName("Setup")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(11)
        self.toolBar.setFont(font)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionNew.setFont(font)
        self.actionNew.setObjectName("actionNew")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionMD5 = QtWidgets.QAction(MainWindow)
        self.actionMD5.setObjectName("actionMD5")
        self.actionPortCheck = QtWidgets.QAction(MainWindow)
        self.actionPortCheck.setObjectName("actionPortCheck")
        self.actionPing = QtWidgets.QAction(MainWindow)
        self.actionPing.setObjectName("actionPing")
        self.actionCancel = QtWidgets.QAction(MainWindow)
        self.actionCancel.setObjectName("actionCancel")
        self.actionDNS = QtWidgets.QAction(MainWindow)
        self.actionDNS.setObjectName("actionDNS")
        self.actionPublicIP = QtWidgets.QAction(MainWindow)
        self.actionPublicIP.setObjectName("actionPublicIP")
        self.actionSystemCheck = QtWidgets.QAction(MainWindow)
        self.actionSystemCheck.setObjectName("actionSystemCheck")
        self.actionDatabaseCheck = QtWidgets.QAction(MainWindow)
        self.actionDatabaseCheck.setObjectName("actionDatabaseCheck")
        self.actionMonitorReport = QtWidgets.QAction(MainWindow)
        self.actionMonitorReport.setObjectName("actionMonitorReport")
        self.actionProperty = QtWidgets.QAction(MainWindow)
        self.actionProperty.setObjectName("actionProperty")
        self.actionAddItem = QtWidgets.QAction(MainWindow)
        self.actionAddItem.setObjectName("actionAddItem")
        self.actionChangeItem = QtWidgets.QAction(MainWindow)
        self.actionChangeItem.setObjectName("actionChangeItem")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionResetPassWord = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.actionResetPassWord.setFont(font)
        self.actionResetPassWord.setObjectName("actionResetPassWord")
        self.File.addAction(self.actionNew)
        self.File.addAction(self.actionExport)
        self.File.addAction(self.actionCancel)
        self.Tool.addAction(self.actionMD5)
        self.Tool.addAction(self.actionPortCheck)
        self.Tool.addAction(self.actionPing)
        self.Tool.addAction(self.actionDNS)
        self.Tool.addAction(self.actionPublicIP)
        self.Help.addAction(self.actionAbout)
        self.Check.addAction(self.actionSystemCheck)
        self.Check.addAction(self.actionDatabaseCheck)
        self.Check.addAction(self.actionMonitorReport)
        self.Setup.addAction(self.actionResetPassWord)
        self.menubar.addAction(self.File.menuAction())
        self.menubar.addAction(self.Check.menuAction())
        self.menubar.addAction(self.Tool.menuAction())
        self.menubar.addAction(self.Setup.menuAction())
        self.menubar.addAction(self.Help.menuAction())
        self.toolBar.addAction(self.actionProperty)
        self.toolBar.addAction(self.actionAddItem)
        self.toolBar.addAction(self.actionChangeItem)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "运维与客户服务部自动运维工具"))
        self.labelProperty.setText(_translate("MainWindow", "资产清单"))
        self.labelPropertyGraph.setText(_translate("MainWindow", "资产图表"))
        self.pushButtonServerPrevPage.setText(_translate("MainWindow", "前一页"))
        self.pushButtonServerNextPage.setText(_translate("MainWindow", "后一页"))
        self.labelSwitchPage.setText(_translate("MainWindow", "转到第"))
        self.labelPage.setText(_translate("MainWindow", "页"))
        self.pushButtonGO.setText(_translate("MainWindow", "GO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "服务器信息"))
        self.pushButtonDBPrevPage.setText(_translate("MainWindow", "前一页"))
        self.pushButtonDBNextPage.setText(_translate("MainWindow", "后一页"))
        self.labelDBSwitchPage.setText(_translate("MainWindow", "转到第"))
        self.labelDBPage.setText(_translate("MainWindow", "页"))
        self.pushButtonDBGO.setText(_translate("MainWindow", "GO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "数据库信息"))
        self.File.setTitle(_translate("MainWindow", "文件"))
        self.Tool.setTitle(_translate("MainWindow", "工具"))
        self.Help.setTitle(_translate("MainWindow", "帮助"))
        self.Check.setTitle(_translate("MainWindow", "巡检"))
        self.Setup.setTitle(_translate("MainWindow", "设置"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "新建"))
        self.actionNew.setToolTip(_translate("MainWindow", "新建文件"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionExport.setText(_translate("MainWindow", "导出"))
        self.actionExport.setToolTip(_translate("MainWindow", "报表导出"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionMD5.setText(_translate("MainWindow", "MD5加密"))
        self.actionMD5.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionPortCheck.setText(_translate("MainWindow", "端口检测"))
        self.actionPortCheck.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionPing.setText(_translate("MainWindow", "Ping连通性检测"))
        self.actionPing.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionCancel.setText(_translate("MainWindow", "关闭"))
        self.actionCancel.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionDNS.setText(_translate("MainWindow", "域名解析"))
        self.actionDNS.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPublicIP.setText(_translate("MainWindow", "公网IP地址解析"))
        self.actionPublicIP.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionSystemCheck.setText(_translate("MainWindow", "系统巡检"))
        self.actionSystemCheck.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionDatabaseCheck.setText(_translate("MainWindow", "数据库巡检"))
        self.actionDatabaseCheck.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionMonitorReport.setText(_translate("MainWindow", "监控报表"))
        self.actionMonitorReport.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionProperty.setText(_translate("MainWindow", "资产清单"))
        self.actionProperty.setToolTip(_translate("MainWindow", "<html><head/><body><p>这可以查看当前中心资产清单！</p></body></html>"))
        self.actionProperty.setShortcut(_translate("MainWindow", "Alt+P"))
        self.actionAddItem.setText(_translate("MainWindow", "信息录入"))
        self.actionAddItem.setToolTip(_translate("MainWindow", "信息录入"))
        self.actionAddItem.setShortcut(_translate("MainWindow", "Alt+A"))
        self.actionChangeItem.setText(_translate("MainWindow", "信息变更"))
        self.actionChangeItem.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionAbout.setText(_translate("MainWindow", "关于我们"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionResetPassWord.setText(_translate("MainWindow", "密码重置"))
        self.actionResetPassWord.setShortcut(_translate("MainWindow", "Ctrl+G"))

from PyQt5 import QtWebEngineWidgets
